const equipoConfig = [
  {
    id: 5,
    name: "KRETZ-NB-046",
    category_id: [2, "Notebooks"],
    employee_id: [31, "Angela Fraga"],
  },
  {
    id: 6,
    name: "KRETZ-NB-036",
    category_id: [2, "Notebooks"],
    employee_id: [40, "Valentin Di Domenica"],
  },
  {
    id: 100,
    name: "KRETZ0414",
    category_id: [2, "Notebooks"],
    employee_id: [36, "Florencia Cerroni"],
  },
  {
    id: 296,
    name: "KRETZ0468",
    category_id: [2, "Notebooks"],
    employee_id: [37, "Nicolas Mateucci"],
  },
  {
    id: 297,
    name: "KRETZ-AIO-001",
    category_id: [5, "All in One"],
    employee_id: [38, "German Psariano"],
  },
  {
    id: 298,
    name: "KRETZ-AIO-002",
    category_id: [5, "All in One"],
    employee_id: [90, "Cristian Pereira"],
  },
  {
    id: 299,
    name: "KRETZ-AIO-003",
    category_id: [5, "All in One"],
    employee_id: [91, "Cristian Castella"],
  },
  {
    id: 300,
    name: "KRETZ-AIO-005",
    category_id: [5, "All in One"],
    employee_id: [29, "Tito Montanari"],
  },
  {
    id: 301,
    name: "KRETZ-AIO-010",
    category_id: [2, "Notebooks"],
    employee_id: [92, "Eduardo Barea"],
  },
  {
    id: 302,
    name: "KRETZ-AIO-011",
    category_id: [2, "Notebooks"],
    employee_id: [93, "Lautaro Martinez"],
  },
  {
    id: 303,
    name: "KRETZ-AIO-012",
    category_id: [2, "Notebooks"],
    employee_id: [94, "Adrian Delorenzi"],
  },
  {
    id: 304,
    name: "KRETZ-AIO-013",
    category_id: [2, "Notebooks"],
    employee_id: [93, "Lautaro Martinez"],
  },
  {
    id: 305,
    name: "KRETZ-NB-001",
    category_id: [2, "Notebooks"],
    employee_id: [95, "Marisel Nievas"],
  },
  {
    id: 306,
    name: "KRETZ-NB-002",
    category_id: [2, "Notebooks"],
    employee_id: [22, "Daniel Kretz"],
  },
  {
    id: 307,
    name: "KRETZ-NB-003",
    category_id: [2, "Notebooks"],
    employee_id: [96, "Bruno Bresca"],
  },
  {
    id: 308,
    name: "KRETZ-NB-004",
    category_id: [2, "Notebooks"],
    employee_id: [97, "Gonzalo Schvindt"],
  },
  {
    id: 309,
    name: "KRETZ-NB-005",
    category_id: [2, "Notebooks"],
    employee_id: [98, "Milton Bazzi"],
  },
  {
    id: 310,
    name: "KRETZ-NB-006",
    category_id: [2, "Notebooks"],
    employee_id: [99, "Sol Suarez"],
  },
  {
    id: 311,
    name: "KRETZ-NB-007",
    category_id: [2, "Notebooks"],
    employee_id: [100, "Mauro Maciel"],
  },
  {
    id: 312,
    name: "KRETZ-NB-008",
    category_id: [2, "Notebooks"],
    employee_id: [101, "Lisandro Nuñez"],
  },
  {
    id: 313,
    name: "KRETZ-NB-009",
    category_id: [2, "Notebooks"],
    employee_id: [93, "Lautaro Martinez"],
  },
  {
    id: 314,
    name: "KRETZ-NB-010",
    category_id: [2, "Notebooks"],
    employee_id: [102, "Violeta Ferri"],
  },
  {
    id: 315,
    name: "KRETZ-NB-011",
    category_id: [2, "Notebooks"],
    employee_id: [103, "Lucas Blas"],
  },
  {
    id: 316,
    name: "KRETZ-NB-012",
    category_id: [2, "Notebooks"],
    employee_id: [39, "Diego Orellano"],
  },
  {
    id: 317,
    name: "KRETZ-NB-013",
    category_id: [2, "Notebooks"],
    employee_id: [104, "Karina Arce"],
  },
  {
    id: 318,
    name: "KRETZ-NB-014",
    category_id: [2, "Notebooks"],
    employee_id: [105, "Lisandro Villarreal"],
  },
  {
    id: 319,
    name: "KRETZ-NB-015",
    category_id: [2, "Notebooks"],
    employee_id: [106, "Diego Costa"],
  },
  {
    id: 320,
    name: "KRETZ-NB-016",
    category_id: [2, "Notebooks"],
    employee_id: [107, "Oriana Villegas"],
  },
  {
    id: 321,
    name: "KRETZ-NB-017",
    category_id: [2, "Notebooks"],
    employee_id: [108, "Daniel Cuello"],
  },
  {
    id: 322,
    name: "KRETZ-NB-018",
    category_id: [2, "Notebooks"],
    employee_id: [109, "Valeria Scantamburlo"],
  },
  {
    id: 323,
    name: "KRETZ-NB-019",
    category_id: [2, "Notebooks"],
    employee_id: [110, "Federico Serra"],
  },
  {
    id: 324,
    name: "KRETZ-NB-020",
    category_id: [2, "Notebooks"],
    employee_id: [111, "Fernando Perez"],
  },
  {
    id: 325,
    name: "KRETZ-NB-021",
    category_id: [2, "Notebooks"],
    employee_id: [112, "Ana Escobar"],
  },
  {
    id: 326,
    name: "KRETZ-NB-022",
    category_id: [2, "Notebooks"],
    employee_id: [113, "Paloma Giorgio"],
  },
  {
    id: 327,
    name: "KRETZ-NB-023",
    category_id: [2, "Notebooks"],
    employee_id: [114, "Nicolas Bella"],
  },
  {
    id: 328,
    name: "KRETZ-NB-025",
    category_id: [2, "Notebooks"],
    employee_id: [115, "Victoria Sampietro"],
  },
  {
    id: 329,
    name: "KRETZ-NB-026",
    category_id: [2, "Notebooks"],
    employee_id: [116, "Santino Cataldi"],
  },
  {
    id: 330,
    name: "KRETZ-NB-027",
    category_id: [2, "Notebooks"],
    employee_id: [35, "Elias Galvan"],
  },
  {
    id: 331,
    name: "KRETZ-NB-028",
    category_id: [2, "Notebooks"],
    employee_id: [117, "Agustina Verdiel"],
  },
  {
    id: 332,
    name: "KRETZ-NB-029",
    category_id: [2, "Notebooks"],
    employee_id: [28, "Regina Calore"],
  },
  {
    id: 333,
    name: "KRETZ-NB-030",
    category_id: [2, "Notebooks"],
    employee_id: [118, "Andrea Giacoboni"],
  },
  {
    id: 334,
    name: "KRETZ-NB-030",
    category_id: [2, "Notebooks"],
    employee_id: [25, "Carolina Perez"],
  },
  {
    id: 335,
    name: "KRETZ-NB-032",
    category_id: [2, "Notebooks"],
    employee_id: [119, "Facundo Piombo"],
  },
  {
    id: 336,
    name: "KRETZ-NB-033",
    category_id: [2, "Notebooks"],
    employee_id: [120, "Pablo Vecchio"],
  },
  {
    id: 337,
    name: "KRETZ-NB-034",
    category_id: [2, "Notebooks"],
    employee_id: [24, "Camilo Rochinotti"],
  },
  {
    id: 338,
    name: "KRETZ-NB-035",
    category_id: [2, "Notebooks"],
    employee_id: [121, "Nestor Marcon"],
  },
  {
    id: 339,
    name: "KRETZ-NB-037",
    category_id: [2, "Notebooks"],
    employee_id: [122, "Daniel Gelmini"],
  },
  {
    id: 340,
    name: "KRETZ-NB-038",
    category_id: [2, "Notebooks"],
    employee_id: [123, "Ernesto Llera"],
  },
  {
    id: 341,
    name: "KRETZ-NB-039",
    category_id: [2, "Notebooks"],
    employee_id: [124, "Nicolas Mazino"],
  },
  {
    id: 342,
    name: "KRETZ-NB-040",
    category_id: [2, "Notebooks"],
    employee_id: [125, "Martin Cintioni"],
  },
  {
    id: 343,
    name: "KRETZ-NB-041",
    category_id: [2, "Notebooks"],
    employee_id: [126, "Pablo Coca"],
  },
  {
    id: 344,
    name: "KRETZ-NB-042",
    category_id: [2, "Notebooks"],
    employee_id: [127, "Luciano Rojas"],
  },
  {
    id: 345,
    name: "KRETZ-NB-043",
    category_id: [2, "Notebooks"],
    employee_id: [127, "Luciano Rojas"],
  },
  {
    id: 346,
    name: "KRETZ-NB-044",
    category_id: [2, "Notebooks"],
    employee_id: [128, "Alexis Casas"],
  },
  {
    id: 347,
    name: "KRETZ-NB-046",
    category_id: [2, "Notebooks"],
    employee_id: [129, "Tomas Wardoloff"],
  },
  {
    id: 348,
    name: "KRETZ-NB-047",
    category_id: [2, "Notebooks"],
    employee_id: [130, "Martin Gonzales"],
  },
  {
    id: 349,
    name: "KRETZ-NB-048",
    category_id: [2, "Notebooks"],
    employee_id: [131, "Sofia Tabaniello"],
  },
  {
    id: 350,
    name: "KRETZ-NB-049",
    category_id: [2, "Notebooks"],
    employee_id: [132, "Alejandro Kleiner"],
  },
  {
    id: 351,
    name: "KRETZ-NB-050",
    category_id: [2, "Notebooks"],
    employee_id: [26, "Luisina Brizuela"],
  },
  {
    id: 352,
    name: "KRETZ-NB-051",
    category_id: [2, "Notebooks"],
    employee_id: [133, "Leonel Vidarte"],
  },
  {
    id: 353,
    name: "KRETZ-NB-052",
    category_id: [2, "Notebooks"],
    employee_id: [134, "Francisco Comparada"],
  },
  {
    id: 354,
    name: "KRETZ-NB-053",
    category_id: [2, "Notebooks"],
    employee_id: [135, "Camila Spitale"],
  },
  {
    id: 355,
    name: "KRETZ-NB-054",
    category_id: [2, "Notebooks"],
    employee_id: [136, "Ismael Alzugaray"],
  },
  {
    id: 356,
    name: "KRETZ-NB-055",
    category_id: [2, "Notebooks"],
    employee_id: [137, "Mauro Medina"],
  },
  {
    id: 357,
    name: "KRETZ-NB-056",
    category_id: [2, "Notebooks"],
    employee_id: [138, "Gustavo Rojas"],
  },
  {
    id: 358,
    name: "KRETZ-NB-057",
    category_id: [2, "Notebooks"],
    employee_id: [33, "Julian Conti"],
  },
  {
    id: 359,
    name: "KRETZ-NB-058",
    category_id: [2, "Notebooks"],
    employee_id: [40, "Valentin Di Domenica"],
  },
  {
    id: 360,
    name: "KRETZ-NB-059",
    category_id: [2, "Notebooks"],
    employee_id: false,
  },
  {
    id: 361,
    name: "KRETZ-NB-060",
    category_id: [2, "Notebooks"],
    employee_id: [139, "Franco Montanari"],
  },
];
export default equipoConfig;
